DROP TABLE ENTITYFORMAT;
DROP TABLE ENTITYDOC;
DROP TABLE ENTITYCUTOUT;

CREATE TABLE ENTITYFORMAT(
IDFORMAT INTEGER PRIMARY KEY AUTO_INCREMENT,
NAMEDOC VARCHAR(50),
DESCDOC VARCHAR(200),
DATECREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
DATEMODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ENTITYDOC(
IDDOC INTEGER PRIMARY KEY AUTO_INCREMENT,
PATHDOC VARCHAR(200),
DATECREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
DATEMODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
IDFORMAT INTEGER,
FOREIGN KEY (IDFORMAT) REFERENCES ENTITYFORMAT(IDFORMAT)
);

CREATE TABLE ENTITYCUTOUT(
IDCUTOUT INTEGER PRIMARY KEY AUTO_INCREMENT,
PATHCUTOUT VARCHAR(200),
DATECREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
DATEMODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
IDDOC INTEGER,
FOREIGN KEY (IDDOC) REFERENCES ENTITYDOC(IDDOC)
);
